### ISSUE TITLE
Add new dental restoration material classes

### ISSUE THREAD

**Issue by wdduncan** [oral-health-and-disease-ontologies/ohd-ontology#88]
New issue for adding dental material classes.

**Comment by gopi-kris** [comment]
@wdduncan, I've added some labels to the annotation properties.

@Nivedita79, Please pull the changes to issue-88 branch. Is 'cement dental restoration material' a material or a role? I need to make some changes to the definition source.

**Comment by Nivedita79** [comment]
'cement dental restoration material'  it is a material.
---------------------------
*Dr. Nivedita Dutta (Chowdhury).*
*B.D.S, PhD*
*Recipient of Women Scientist fellowship, DST, Govt. of India *
*Dental Surgeon, Clinical Researcher*
*Durgapur -713213*

*Orcid ID: https://orcid.org/0000-0001-6424-4096
<https://orcid.org/0000-0001-6424-4096>*

**Comment by Nivedita79** [comment]
'cement dental restoration material' is a material.

**Comment by wdduncan** [comment]
@Nivedita79 please language mentioning ISO standards with the relevant language from the ISO.  
- zinc oxide dental restoration material (OHD_0001022)
- acid-base cement dental restoration material (OHD_0001021)

The ISO standard can be added as hasDbXref annotation. E.g., see resin-based cement dental restoration material (OHD_0001005).

<img width="862" alt="image" src="https://github.com/oral-health-and-disease-ontologies/ohd-ontology/assets/3186638/db553d4a-0362-455a-b9c2-719575488931">

**Comment by Nivedita79** [comment]
Okay
---------------------------
*Dr. Nivedita Dutta (Chowdhury).*
*B.D.S, PhD*
*Recipient of Women Scientist fellowship, DST, Govt. of India *
*Dental Surgeon, Clinical Researcher*
*Durgapur -713213*

*Orcid ID: https://orcid.org/0000-0001-6424-4096
<https://orcid.org/0000-0001-6424-4096>*

**Comment by wdduncan** [comment]
@Nivedita79 @gopi-kris 
I went through the dental_material import. I found the following issues:
- Should the definition for 'glass ionomer cement dental restoration material' read "An acid-base cement dental restoration material that has three ..."?
- 'conventional glass ionomer cement dental restoration material' needs a defintion.
- The definition for 'metal modified glass ionomer dental restoration material' is not in genus-differentia form.
- 'zinc phosphate cement dental restoration material' needs a definition.
- 'zinc polycarboxylate cement dental restoration material' needs a definition.
- 'calcium hydroxide cement dental restoration material' needs a definition.
- 'mineral trioxide aggregate cement dental restoration material' needs a definition. Didn't we discuss not having MTA in the ontology right now? I can't recall.
- Can you review the definition of 'zinc oxide dental restoration material'?

After we address these issues, I think we can merge the PR.

**Comment by gopi-kris** [comment]
@wdduncan, for MTA, the main point of confusion was whether it needs to come under a medications category since it helps in dentine formation. However, since it is used as part of the restoration process, we can include it as a separate class here.

**Comment by wdduncan** [comment]
Thanks @gopi-kris  
Are you able to provide a definition for MTA?

**Comment by wdduncan** [comment]
Let's close this for now. A number of updates were made in https://github.com/oral-health-and-disease-ontologies/ohd-ontology/pull/112. We can create new issues for new updates.
