### ISSUE TITLE
Updating MAINTAINERS.md to include instructions for creating new entities

### ISSUE THREAD

**Issue by gopi-kris** [oral-health-and-disease-ontologies/ohd-ontology#95]
Instructions are needed for new users to configure Protege so that the name is appropriately added when they create a new entity. If Protege is not configured properly then new entity names are auto-generated using a globally unique URL-safe identifier that is the default setting in Protege, rather than numeric identifiers.

**Comment by matentzn** [comment]
To satisfy https://github.com/oral-health-and-disease-ontologies/ohd-ontology/community

the file should be called CONTRIBUTING.md instead! There is a nice one I can autogenerate with ODK!

**Comment by wdduncan** [comment]
> the file should be called CONTRIBUTING.md instead!   

I thought `CONTRIBUTING.md` was mainly about how external users can submit content to be added to the repo. E.g., submitting an issue on the tracker.

The `MAINTAINERS.md`, on the other hand, was about the technical details for editors of the ontology. Did this change?

**Comment by gopi-kris** [comment]
@matentzn and @wdduncan, I've created a draft pull request with a separate CONTRIBUTING.md file for now. I can move the existing documentation to MAINTAINERS.md later if you want.

**Comment by matentzn** [comment]
@wdduncan you are right in principle, but the descriptions `for new users to configure Protege` sounded like it was more general. I would put all contribution information in CONTRIBUTING.md, and information about who the maintainers are in MAINTAINERS.md. For the rest, you will get a specific documentation system with an editors guide etc after the migration to ODK is done, like https://pato-ontology.github.io/pato/

**Comment by gopi-kris** [comment]
@wdduncan, should I move the content from maintainers.md to contributing.md?

**Comment by wdduncan** [comment]
@gopi-kris Yes. Please go ahead and move it. Thanks!
